### ISSUE TITLE
LocationService going down after 5 minute idle

### ISSUE THREAD

**Issue by AdamFM** [nickfox/GpsTracker#92]
`11-18 20:46:19.305 21367-21367/com.websmithing.gpstracker E/LocationService: position: -6.2643888, 106.8750638 accuracy: 20.0
11-18 20:46:21.645 21367-21367/com.websmithing.gpstracker W/IInputConnectionWrapper: showStatusIcon on inactive InputConnection
11-18 20:46:22.745 21367-21367/com.websmithing.gpstracker V/AsyncHttpRH: Progress 19 from 1 (1900%)
11-18 20:46:22.755 21367-21367/com.websmithing.gpstracker D/LocationService: https://www.websmithing.com/gpstracker/updatelocation.php?date=2017-11-18%2B20%253A46%253A19&distance=0.0&latitude=-6.2643888&phonenumber=24416d84-a7f7-423e-bf0a-b8e9374840af&accuracy=65&sessionid=91c17a62-5dad-44ce-a755-0b30dfb88dc5&speed=0&extrainfo=0&eventtype=android&locationmethod=fused&longitude=106.8750638&username=SsTes&direction=0
11-18 20:46:22.755 21367-21367/com.websmithing.gpstracker E/LocationService: sendLocationDataToWebsite - success
11-18 20:46:22.755 21367-21367/com.websmithing.gpstracker D/LocationService: Return Headers:
11-18 20:46:22.755 21367-21367/com.websmithing.gpstracker E/LocationService: StatusCode: 200
11-18 20:46:22.755 21367-21367/com.websmithing.gpstracker D/LocationService: Response: 2017-11-18 05:46:22
11-18 20:47:19.573 21367-21367/com.websmithing.gpstracker D/LocationService: startTracking
11-18 20:47:19.593 21367-21367/com.websmithing.gpstracker D/LocationService: onConnected
11-18 20:47:19.613 21367-21367/com.websmithing.gpstracker E/LocationService: position: -6.2643888, 106.8750638 accuracy: 20.0
11-18 20:47:20.013 21367-21367/com.websmithing.gpstracker V/AsyncHttpRH: Progress 19 from 1 (1900%)
11-18 20:47:20.013 21367-21367/com.websmithing.gpstracker D/LocationService: https://www.websmithing.com/gpstracker/updatelocation.php?date=2017-11-18%2B20%253A47%253A19&distance=0.0&latitude=-6.2643888&phonenumber=24416d84-a7f7-423e-bf0a-b8e9374840af&accuracy=65&sessionid=91c17a62-5dad-44ce-a755-0b30dfb88dc5&speed=0&extrainfo=0&eventtype=android&locationmethod=fused&longitude=106.8750638&username=SsTes&direction=0
11-18 20:47:20.013 21367-21367/com.websmithing.gpstracker E/LocationService: sendLocationDataToWebsite - success
11-18 20:47:20.013 21367-21367/com.websmithing.gpstracker D/LocationService: Return Headers:
11-18 20:47:20.013 21367-21367/com.websmithing.gpstracker E/LocationService: StatusCode: 200
11-18 20:47:20.013 21367-21367/com.websmithing.gpstracker D/LocationService: Response: 2017-11-18 05:47:19
11-18 20:48:17.245 21367-21367/com.websmithing.gpstracker D/LocationService: startTracking
11-18 20:48:17.265 21367-21367/com.websmithing.gpstracker D/LocationService: onConnected
11-18 20:48:17.295 21367-21367/com.websmithing.gpstracker E/LocationService: position: -6.2643888, 106.8750638 accuracy: 20.0
11-18 20:48:17.715 21367-21367/com.websmithing.gpstracker V/AsyncHttpRH: Progress 19 from 1 (1900%)
11-18 20:48:17.715 21367-21367/com.websmithing.gpstracker D/LocationService: https://www.websmithing.com/gpstracker/updatelocation.php?date=2017-11-18%2B20%253A48%253A17&distance=0.0&latitude=-6.2643888&phonenumber=24416d84-a7f7-423e-bf0a-b8e9374840af&accuracy=65&sessionid=91c17a62-5dad-44ce-a755-0b30dfb88dc5&speed=0&extrainfo=0&eventtype=android&locationmethod=fused&longitude=106.8750638&username=SsTes&direction=0
11-18 20:48:17.715 21367-21367/com.websmithing.gpstracker E/LocationService: sendLocationDataToWebsite - success
11-18 20:48:17.715 21367-21367/com.websmithing.gpstracker D/LocationService: Return Headers:
11-18 20:48:17.715 21367-21367/com.websmithing.gpstracker E/LocationService: StatusCode: 200
11-18 20:48:17.715 21367-21367/com.websmithing.gpstracker D/LocationService: Response: 2017-11-18 05:48:18
11-18 20:49:17.251 21367-21367/com.websmithing.gpstracker D/LocationService: startTracking
11-18 20:49:17.271 21367-21367/com.websmithing.gpstracker D/LocationService: onConnected
11-18 20:49:17.281 21367-21367/com.websmithing.gpstracker E/LocationService: position: -6.2643888, 106.8750638 accuracy: 20.0
11-18 20:49:17.691 21367-21367/com.websmithing.gpstracker V/AsyncHttpRH: Progress 19 from 1 (1900%)
11-18 20:49:17.691 21367-21367/com.websmithing.gpstracker D/LocationService: https://www.websmithing.com/gpstracker/updatelocation.php?date=2017-11-18%2B20%253A49%253A17&distance=0.0&latitude=-6.2643888&phonenumber=24416d84-a7f7-423e-bf0a-b8e9374840af&accuracy=65&sessionid=91c17a62-5dad-44ce-a755-0b30dfb88dc5&speed=0&extrainfo=0&eventtype=android&locationmethod=fused&longitude=106.8750638&username=SsTes&direction=0
11-18 20:49:17.691 21367-21367/com.websmithing.gpstracker E/LocationService: sendLocationDataToWebsite - success
11-18 20:49:17.691 21367-21367/com.websmithing.gpstracker D/LocationService: Return Headers:
11-18 20:49:17.691 21367-21367/com.websmithing.gpstracker E/LocationService: StatusCode: 200
11-18 20:49:17.691 21367-21367/com.websmithing.gpstracker D/LocationService: Response: 2017-11-18 05:49:17
11-18 20:50:17.247 21367-21367/com.websmithing.gpstracker D/LocationService: startTracking
11-18 20:50:17.267 21367-21367/com.websmithing.gpstracker D/LocationService: onConnected
11-18 20:50:17.287 21367-21367/com.websmithing.gpstracker E/LocationService: position: -6.2643888, 106.8750638 accuracy: 20.0
11-18 20:50:27.667 21367-1903/com.websmithing.gpstracker W/System.err: java.net.SocketTimeoutException: Read timed out
11-18 20:50:27.667 21367-1903/com.websmithing.gpstracker W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
11-18 20:50:27.667 21367-1903/com.websmithing.gpstracker W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:674)
11-18 20:50:27.667 21367-1903/com.websmithing.gpstracker W/System.err:     at cz.msebera.android.httpclient.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:160)
11-18 20:50:27.667 21367-1903/com.websmithing.gpstracker W/System.err:     at cz.msebera.android.httpclient.impl.io.SocketInputBuffer.fillBuffer(SocketInputBuffer.java:84)
11-18 20:50:27.667 21367-1903/com.websmithing.gpstracker W/System.err:     at cz.msebera.android.httpclient.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.java:273)
11-18 20:50:27.667 21367-1903/com.websmithing.gpstracker W/System.err:     at cz.msebera.android.httpclient.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
11-18 20:50:27.667 21367-1903/com.websmithing.gpstracker W/System.err:     at cz.msebera.android.httpclient.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
11-18 20:50:27.667 21367-1903/com.websmithing.gpstracker W/System.err:     at cz.msebera.android.httpclient.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
11-18 20:50:27.667 21367-1903/com.websmithing.gpstracker W/System.err:     at cz.msebera.android.httpclient.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:283)
11-18 20:50:27.667 21367-1903/com.websmithing.gpstracker W/System.err:     at cz.msebera.android.httpclient.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:251)
11-18 20:50:27.667 21367-1903/com.websmithing.gpstracker W/System.err:     at cz.msebera.android.httpclient.impl.conn.AbstractClientConnAdapter.receiveResponseHeader(AbstractClientConnAdapter.java:223)
11-18 20:50:27.667 21367-1903/com.websmithing.gpstracker W/System.err:     at cz.msebera.android.httpclient.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271)
11-18 20:50:27.667 21367-1903/com.websmithing.gpstracker W/System.err:     at cz.msebera.android.httpclient.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
11-18 20:50:27.667 21367-1903/com.websmithing.gpstracker W/System.err:     at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:685)
11-18 20:50:27.667 21367-1903/com.websmithing.gpstracker W/System.err:     at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:487)
11-18 20:50:27.667 21367-1903/com.websmithing.gpstracker W/System.err:     at cz.msebera.android.httpclient.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:860)
11-18 20:50:27.667 21367-1903/com.websmithing.gpstracker W/System.err:     at cz.msebera.android.httpclient.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
11-18 20:50:27.667 21367-1903/com.websmithing.gpstracker W/System.err:     at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:146)
11-18 20:50:27.667 21367-1903/com.websmithing.gpstracker W/System.err:     at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:177)
11-18 20:50:27.667 21367-1903/com.websmithing.gpstracker W/System.err:     at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:106)
11-18 20:50:27.667 21367-1903/com.websmithing.gpstracker W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
11-18 20:50:27.667 21367-1903/com.websmithing.gpstracker W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
11-18 20:50:27.667 21367-1903/com.websmithing.gpstracker W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
11-18 20:50:27.667 21367-1903/com.websmithing.gpstracker W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
11-18 20:50:27.667 21367-1903/com.websmithing.gpstracker W/System.err:     at java.lang.Thread.run(Thread.java:818)
11-18 20:50:27.677 21367-1903/com.websmithing.gpstracker W/System.err: java.net.SocketTimeoutException: Read timed out
11-18 20:50:27.677 21367-1903/com.websmithing.gpstracker W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
11-18 20:50:27.677 21367-1903/com.websmithing.gpstracker W/System.err:     at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:674)
11-18 20:50:27.677 21367-1903/com.websmithing.gpstracker W/System.err:     at cz.msebera.android.httpclient.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:160)
11-18 20:50:27.677 21367-1903/com.websmithing.gpstracker W/System.err:     at cz.msebera.android.httpclient.impl.io.SocketInputBuffer.fillBuffer(SocketInputBuffer.java:84)
11-18 20:50:27.677 21367-1903/com.websmithing.gpstracker W/System.err:     at cz.msebera.android.httpclient.impl.io.AbstractSessionInputBuffer.readLine(AbstractSessionInputBuffer.java:273)
11-18 20:50:27.677 21367-1903/com.websmithing.gpstracker W/System.err:     at cz.msebera.android.httpclient.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
11-18 20:50:27.677 21367-1903/com.websmithing.gpstracker W/System.err:     at cz.msebera.android.httpclient.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
11-18 20:50:27.677 21367-1903/com.websmithing.gpstracker W/System.err:     at cz.msebera.android.httpclient.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
11-18 20:50:27.677 21367-1903/com.websmithing.gpstracker W/System.err:     at cz.msebera.android.httpclient.impl.AbstractHttpClientConnection.receiveResponseHeader(AbstractHttpClientConnection.java:283)
11-18 20:50:27.677 21367-1903/com.websmithing.gpstracker W/System.err:     at cz.msebera.android.httpclient.impl.conn.DefaultClientConnection.receiveResponseHeader(DefaultClientConnection.java:251)
11-18 20:50:27.677 21367-1903/com.websmithing.gpstracker W/System.err:     at cz.msebera.android.httpclient.impl.conn.AbstractClientConnAdapter.receiveResponseHeader(AbstractClientConnAdapter.java:223)
11-18 20:50:27.677 21367-1903/com.websmithing.gpstracker W/System.err:     at cz.msebera.android.httpclient.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271)
11-18 20:50:27.677 21367-1903/com.websmithing.gpstracker W/System.err:     at cz.msebera.android.httpclient.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
11-18 20:50:27.677 21367-1903/com.websmithing.gpstracker W/System.err:     at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.tryExecute(DefaultRequestDirector.java:685)
11-18 20:50:27.677 21367-1903/com.websmithing.gpstracker W/System.err:     at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:487)
11-18 20:50:27.677 21367-1903/com.websmithing.gpstracker W/System.err:     at cz.msebera.android.httpclient.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:860)
11-18 20:50:27.677 21367-1903/com.websmithing.gpstracker W/System.err:     at cz.msebera.android.httpclient.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
11-18 20:50:27.677 21367-1903/com.websmithing.gpstracker W/System.err:     at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:146)
11-18 20:50:27.677 21367-1903/com.websmithing.gpstracker W/System.err:     at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:177)
11-18 20:50:27.677 21367-1903/com.websmithing.gpstracker W/System.err:     at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:106)
11-18 20:50:27.677 21367-1903/com.websmithing.gpstracker W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
11-18 20:50:27.677 21367-1903/com.websmithing.gpstracker W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
11-18 20:50:27.677 21367-1903/com.websmithing.gpstracker W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
11-18 20:50:27.677 21367-1903/com.websmithing.gpstracker W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
11-18 20:50:27.677 21367-1903/com.websmithing.gpstracker W/System.err:     at java.lang.Thread.run(Thread.java:818)
11-18 20:50:27.677 21367-21367/com.websmithing.gpstracker D/LocationService: https://www.websmithing.com/gpstracker/updatelocation.php?date=2017-11-18%2B20%253A50%253A17&distance=0.0&latitude=-6.2643888&phonenumber=24416d84-a7f7-423e-bf0a-b8e9374840af&accuracy=65&sessionid=91c17a62-5dad-44ce-a755-0b30dfb88dc5&speed=0&extrainfo=0&eventtype=android&locationmethod=fused&longitude=106.8750638&username=SsTes&direction=0
11-18 20:51:17.252 21367-21367/com.websmithing.gpstracker D/LocationService: startTracking
11-18 20:51:17.282 21367-21367/com.websmithing.gpstracker D/LocationService: onConnected
11-18 20:51:17.542 21367-21367/com.websmithing.gpstracker E/LocationService: position: -6.2643888, 106.8750638 accuracy: 20.0
11-18 20:51:25.344 21367-1903/com.websmithing.gpstracker W/System.err: java.net.UnknownHostException: Unable to resolve host "www.websmithing.com": No address associated with hostname
11-18 20:51:25.344 21367-1903/com.websmithing.gpstracker W/System.err:     at java.net.InetAddress.lookupHostByName(InetAddress.java:427)
11-18 20:51:25.344 21367-1903/com.websmithing.gpstracker W/System.err:     at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
11-18 20:51:25.344 21367-1903/com.websmithing.gpstracker W/System.err:     at java.net.InetAddress.getAllByName(InetAddress.java:215)
11-18 20:51:25.344 21367-1903/com.websmithing.gpstracker W/System.err:     at cz.msebera.android.httpclient.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:44)
11-18 20:51:25.344 21367-1903/com.websmithing.gpstracker W/System.err:     at cz.msebera.android.httpclient.impl.conn.DefaultClientConnectionOperator.resolveHostname(DefaultClientConnectionOperator.java:259)
11-18 20:51:25.344 21367-1903/com.websmithing.gpstracker W/System.err:     at cz.msebera.android.httpclient.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:159)
11-18 20:51:25.344 21367-1903/com.websmithing.gpstracker W/System.err:     at cz.msebera.android.httpclient.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:145)
11-18 20:51:25.344 21367-1903/com.websmithing.gpstracker W/System.err:     at cz.msebera.android.httpclient.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:131)
11-18 20:51:25.344 21367-1903/com.websmithing.gpstracker W/System.err:     at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:611)
11-18 20:51:25.344 21367-1903/com.websmithing.gpstracker W/System.err:     at cz.msebera.android.httpclient.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:446)
11-18 20:51:25.344 21367-1903/com.websmithing.gpstracker W/System.err:     at cz.msebera.android.httpclient.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:860)
11-18 20:51:25.344 21367-1903/com.websmithing.gpstracker W/System.err:     at cz.msebera.android.httpclient.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
11-18 20:51:25.344 21367-1903/com.websmithing.gpstracker W/System.err:     at com.loopj.android.http.AsyncHttpRequest.makeRequest(AsyncHttpRequest.java:146)
11-18 20:51:25.344 21367-1903/com.websmithing.gpstracker W/System.err:     at com.loopj.android.http.AsyncHttpRequest.makeRequestWithRetries(AsyncHttpRequest.java:177)
11-18 20:51:25.344 21367-1903/com.websmithing.gpstracker W/System.err:     at com.loopj.android.http.AsyncHttpRequest.run(AsyncHttpRequest.java:106)
11-18 20:51:25.344 21367-1903/com.websmithing.gpstracker W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
11-18 20:51:25.344 21367-1903/com.websmithing.gpstracker W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
11-18 20:51:25.344 21367-1903/com.websmithing.gpstracker W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
11-18 20:51:25.344 21367-1903/com.websmithing.gpstracker W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
11-18 20:51:25.344 21367-1903/com.websmithing.gpstracker W/System.err:     at java.lang.Thread.run(Thread.java:818)
11-18 20:51:25.354 21367-21367/com.websmithing.gpstracker D/LocationService: https://www.websmithing.com/gpstracker/updatelocation.php?date=2017-11-18%2B20%253A51%253A17&distance=0.0&latitude=-6.2643888&phonenumber=24416d84-a7f7-423e-bf0a-b8e9374840af&accuracy=65&sessionid=91c17a62-5dad-44ce-a755-0b30dfb88dc5&speed=0&extrainfo=0&eventtype=android&locationmethod=fused&longitude=106.8750638&username=SsTes&direction=0
`

Error

**Comment by nickfox** [comment]
Once you get the error, how often does it happen?

n

**Comment by AdamFM** [comment]
always happens like that when the app is not open..
